package com.dslab.drs.socket;

public enum ResponseType {
  APPCLI_ASK_PROGRESS, DRSCLI_KILL, APPCLI_REGISTER, WATCH_REQ, PROGRESS, REGISTER,
  NEW_TASK, FAILED_TASK, DONE_TASK, SCHEDULE_SUCCESS, ASK_STATUS, CONTAINER_WAIT, WRONG_REQ
}
